name: CI
on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: annakonn200059/job-tracker-ci/.github/workflows/python.yml@v1.0.0
  image:
    needs: [ci]
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: annakonn200059/job-tracker-ci/.github/workflows/image.yml@v1.0.0
    with:
      image-name: job-tracker-worker
